/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cliente;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author ANDY
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
   //LOGIN 
   
    
    //INTERFAZ
    Login login = new Login();
  
    public Interfaz() {
        initComponents();
            this.setLocationRelativeTo(this);
            
            ImageIcon icon = new ImageIcon("src/Ima/2.png"); // Ruta del icono
        setIconImage(icon.getImage());
        
         SetImageButton(Enviarbtn, "src/Ima/4.png");
         SetImageButton(Salirbtn, "src/Ima/5.png");
            
  String elpuerto = puertolbl.getText();
    String rutaProyecto = System.getProperty("user.dir");
    String archivo= rutaProyecto+"\\src\\Doc\\"+elpuerto;
            
  
            
            
         /*CREAR ARCHIVO*/   
            try {
                System.out.println(archivo+"    este es el directorio buscado");
              File  archivod = new File (archivo);
              boolean existe= archivod.exists();
              
              
              if (existe) {
            try {
                archivod.createNewFile();
                System.out.println("El archivo " + archivod + " ha sido creado.");
            } catch (Exception e) {
                System.out.println("Error al crear el archivo: " + e.getMessage());
            }
        }else{
                    System.out.println("Ya esta creado");
                    }
              
              
              
              
        } catch (Exception e) {
                System.out.println(e.getMessage());
        }
            /*CIERRE DE CREAR ARCHIVO*/
    }

    
        private void SetImageButton(JButton button, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(button.getWidth(), button.getHeight(), Image.SCALE_SMOOTH));
        button.setIcon(icon);
       
        
        button.setBorderPainted(false);
        button.setContentAreaFilled(false);
        button.setFocusPainted(false);
        button.setOpaque(false);
        this.repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        historialMentxt = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        mensajetxt = new javax.swing.JTextArea();
        Enviarbtn = new javax.swing.JButton();
        Salirbtn = new javax.swing.JButton();
        participantesbtn = new javax.swing.JButton();
        Mensajebtn = new javax.swing.JButton();
        usuariootxt = new javax.swing.JTextField();
        puertolbl = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        participantestxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(202, 193, 245));

        jLabel1.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(82, 77, 105));
        jLabel1.setText("Participantes:");

        jLabel2.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(82, 77, 105));
        jLabel2.setText("Mensajes");

        historialMentxt.setEditable(false);
        historialMentxt.setBackground(new java.awt.Color(213, 205, 250));
        historialMentxt.setColumns(20);
        historialMentxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        historialMentxt.setForeground(new java.awt.Color(82, 77, 105));
        historialMentxt.setRows(5);
        historialMentxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setViewportView(historialMentxt);

        mensajetxt.setColumns(20);
        mensajetxt.setRows(5);
        jScrollPane3.setViewportView(mensajetxt);

        Enviarbtn.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        Enviarbtn.setForeground(new java.awt.Color(82, 77, 105));
        Enviarbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Enviarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Enviarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarbtnActionPerformed(evt);
            }
        });

        Salirbtn.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        Salirbtn.setForeground(new java.awt.Color(82, 77, 105));
        Salirbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Salirbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirbtnActionPerformed(evt);
            }
        });

        participantesbtn.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        participantesbtn.setForeground(new java.awt.Color(82, 77, 105));
        participantesbtn.setText("Lista  Participantes");
        participantesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantesbtnActionPerformed(evt);
            }
        });

        Mensajebtn.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        Mensajebtn.setForeground(new java.awt.Color(82, 77, 105));
        Mensajebtn.setText("Lista  Mensaje");
        Mensajebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MensajebtnActionPerformed(evt);
            }
        });

        usuariootxt.setEditable(false);
        usuariootxt.setBackground(new java.awt.Color(175, 167, 214));
        usuariootxt.setForeground(new java.awt.Color(110, 107, 126));
        usuariootxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        puertolbl.setEditable(false);
        puertolbl.setBackground(new java.awt.Color(175, 167, 214));
        puertolbl.setForeground(new java.awt.Color(110, 107, 126));
        puertolbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        participantestxt.setEditable(false);
        participantestxt.setBackground(new java.awt.Color(213, 205, 250));
        participantestxt.setColumns(20);
        participantestxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        participantestxt.setForeground(new java.awt.Color(82, 77, 105));
        participantestxt.setRows(5);
        participantestxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane4.setViewportView(participantestxt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(participantesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Mensajebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Enviarbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Salirbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)))
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(puertolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usuariootxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuariootxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puertolbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Enviarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Salirbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(participantesbtn)
                        .addComponent(Mensajebtn)))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirbtnActionPerformed
        // TODO add your handling code here:
        // Obtener el nombre de usuario
    String nombreUsuario = usuariootxt.getText();
    
    // Ruta del archivo "historial de mensajes"
    String rutaArchivo = System.getProperty("user.dir") + "\\src\\Doc\\Historial_mensajes.txt";
    
    try {
        // Crear un nuevo archivo temporal para almacenar los nombres de usuario
        File archivoTemporal = new File("temporal.txt");
        FileWriter fw = new FileWriter(archivoTemporal);
        BufferedWriter bw = new BufferedWriter(fw);
        
        // Leer el archivo original línea por línea
        FileReader fr = new FileReader(rutaArchivo);
        BufferedReader br = new BufferedReader(fr);
        String linea;
        
        while ((linea = br.readLine()) != null) {
            // Si la línea no contiene el nombre de usuario, escribir la línea en el archivo temporal
            if (!linea.trim().equals(nombreUsuario)) {
                bw.write(linea);
                bw.newLine();
            }
        }
        
        // Cerrar los flujos de lectura y escritura
        br.close();
        bw.close();
        
        // Eliminar el archivo original
        File archivoOriginal = new File(rutaArchivo);
        archivoOriginal.delete();
        
        // Renombrar el archivo temporal al nombre original
        archivoTemporal.renameTo(archivoOriginal);
        
    } catch (IOException ex) {
        // Manejar cualquier excepción de IO
        ex.printStackTrace();
    }
        
        
        
        System.exit(0);
    }//GEN-LAST:event_SalirbtnActionPerformed

    private void MensajebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MensajebtnActionPerformed
        Driver miDriver = new Driver("localhost",Integer.parseInt(puertolbl.getText()));
         String perto = puertolbl.getText();
        String mensaje=miDriver.cargar(perto);
        
        historialMentxt.setText(mensaje);      
    }//GEN-LAST:event_MensajebtnActionPerformed

    private void EnviarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarbtnActionPerformed
        // TODO add your handling code here:
        boolean existe = mensajetxt.getText().trim().length()>0;
        String texto = mensajetxt.getText();
        
       
        
        if(existe==true){
             String mensaje = usuariootxt.getText()+": "+texto
                     +"."+"\r\n";
                historialMentxt.append(mensaje);
                mensajetxt.setText(null);
            try {
                escribirMensajeEnArchivo(mensaje);               
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
                
        }else{
            JOptionPane.showMessageDialog(null, "No hay nada que enviar");
        }
        
        
        
    }//GEN-LAST:event_EnviarbtnActionPerformed

    private void participantesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantesbtnActionPerformed
      Driver miDriver = new Driver("localhost",Integer.parseInt(puertolbl.getText()));
        String mensajito;
        mensajito = miDriver.Lista(usuariootxt.getText());
        participantestxt.setText(mensajito);
        
        
        
       
    }//GEN-LAST:event_participantesbtnActionPerformed

        // Método para escribir el mensaje en un archivo  ddd
    private void escribirMensajeEnArchivo(String mensaje) throws java.io.IOException {
       
          String elpuerto = puertolbl.getText();
    String rutaProyecto = System.getProperty("user.dir");
    String archivo= rutaProyecto+"\\src\\Doc\\"+elpuerto;
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivo, true))) {
            writer.write(mensaje);
           
        } catch (Exception e) {
            // Manejar cualquier error de escritura en el archivo
            System.out.println(e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviarbtn;
    private javax.swing.JButton Mensajebtn;
    private javax.swing.JButton Salirbtn;
    public javax.swing.JTextArea historialMentxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea mensajetxt;
    private javax.swing.JButton participantesbtn;
    public javax.swing.JTextArea participantestxt;
    public javax.swing.JTextField puertolbl;
    public javax.swing.JTextField usuariootxt;
    // End of variables declaration//GEN-END:variables
}
